-- Project Name:- Grocery Store System


-- 0.CREATE DATABASE
CREATE DATABASE IF NOT EXISTS grocery_store CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
use grocery_store;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

select * from supplier;


-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

select * from  categories;


-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

select *from employees;


-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

select * from customers;

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from products ;

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from orders;


-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT ,
    prod_id TINYINT ,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from order_details;

select * from categories;

select * from customers;

select * from employees;

select* from orders;

select * from products;

select * from order_details;

select * from supplier;



--  Analysis Questions:-


-- Q.1️. Customer Insights
-- i) How many unique customers have placed orders?
SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM orders;

-- Q.7. Which customers have placed the highest number of orders?

SELECT c.cust_id, c.cust_name, COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_orders DESC;


-- iii) What is the total and average purchase value per customer?
SELECT c.cust_id, c.cust_name,
       SUM(od.total_price) AS total_purchase,
       AVG(od.total_price) AS avg_purchase
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase DESC;

-- Q.8) Who are the top 5 customers by total purchase amount?
SELECT c.cust_id, c.cust_name, SUM(od.total_price) AS total_purchase
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase DESC
LIMIT 5;

-- 2. Product Performance
-- i) How many products exist in each category?
SELECT cat_id, COUNT(*) AS total_products
FROM products
GROUP BY cat_id;

-- Q.9) What is the average price of products by category?
SELECT cat_id, AVG(price) AS avg_price
FROM products
GROUP BY cat_id;


-- 2. Product Performance
-- i) Which products have the highest total sales volume (by quantity)?
SELECT p.prod_id, p.prod_name, SUM(od.quantity) AS total_quantity
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_quantity DESC;

-- iv) What is the total revenue generated by each product?
SELECT p.prod_id, p.prod_name, SUM(od.total_price) AS total_revenue
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_revenue DESC;

-- v) How do product sales vary by category and supplier?
SELECT c.cat_name, s.sup_name, p.prod_name, SUM(od.quantity) AS total_quantity, SUM(od.total_price) AS total_revenue
FROM products p
JOIN categories c ON p.cat_id = c.cat_id
JOIN supplier s ON p.sup_id = s.sup_id
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY c.cat_name, s.sup_name, p.prod_name
ORDER BY total_revenue DESC;

-- 3.Sales and Order Trends
-- i) How many orders have been placed in total?
SELECT COUNT(*) AS total_orders
FROM orders;

-- ii) What is the average value per order?
SELECT o.ord_id, SUM(od.total_price) AS order_total
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY o.ord_id;

-- iii) (Or for overall average):
SELECT AVG(order_total) AS avg_order_value
FROM (
    SELECT o.ord_id, SUM(od.total_price) AS order_total
    FROM orders o
    JOIN order_details od ON o.ord_id = od.ord_id
    GROUP BY o.ord_id
) AS sub;

-- Q.3.Sales and Order Trends
-- iv) On which dates were the most orders placed?
SELECT order_date, COUNT(*) AS num_orders
FROM orders
GROUP BY order_date
ORDER BY num_orders DESC;

-- v) What are the monthly trends in order volume and revenue?
SELECT DATE_FORMAT(order_date, '%Y-%m') AS month,
       COUNT(DISTINCT o.ord_id) AS total_orders,
       SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY month
ORDER BY month;


-- vi) How do order patterns vary across weekdays and weekends?
SELECT DAYNAME(order_date) AS weekday,
       COUNT(DISTINCT o.ord_id) AS total_orders,
       SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY weekday
ORDER BY FIELD(weekday,'Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday');



-- 4️. Supplier Contribution

-- 10) How many suppliers are there in the database?
SELECT COUNT(*) AS total_suppliers
FROM supplier;

-- Q.4️. Supplier Contribution
-- ii) Which supplier provides the most products?
SELECT s.sup_id, s.sup_name, COUNT(p.prod_id) AS total_products
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_products DESC;


-- iii) What is the average price of products from each supplier?
SELECT s.sup_name, AVG(p.price) AS avg_price
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_name;


-- iv) Which suppliers contribute the most to total product sales (by revenue)?
SELECT s.sup_name, SUM(od.total_price) AS total_sales
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY s.sup_name
ORDER BY total_sales DESC;

-- 5️. Employee Performance
-- i) How many employees have processed orders?
SELECT COUNT(DISTINCT emp_id) AS active_employees
FROM orders;

-- Q.5️. Employee Performance
-- ii) Which employees have handled the most orders?
SELECT e.emp_id, e.emp_name, COUNT(o.ord_id) AS total_orders
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_orders DESC;


-- iii) What is the total sales value processed by each employee?
SELECT e.emp_name, SUM(od.total_price) AS total_sales
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_name
ORDER BY total_sales DESC;


-- iv) What is the average order value handled per employee?
SELECT e.emp_name, AVG(order_total) AS avg_order_value
FROM employees e
JOIN (
    SELECT o.ord_id, o.emp_id, SUM(od.total_price) AS order_total
    FROM orders o
    JOIN order_details od ON o.ord_id = od.ord_id
    GROUP BY o.ord_id
) AS sub ON e.emp_id = sub.emp_id
GROUP BY e.emp_name;

-- 6️. Order Details Deep Dive
-- i) What is the relationship between quantity ordered and total price?
SELECT quantity, total_price
FROM order_details;

-- ii) What is the average quantity ordered per product?
SELECT p.prod_name, AVG(od.quantity) AS avg_quantity
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_name;

-- Q.6. Order Details Deep Dive
-- iii) How does the unit price vary across products and orders?
SELECT p.prod_name, od.each_price, COUNT(*) AS occurrences
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_name, od.each_price
ORDER BY p.prod_name, od.each_price;




